age = input('What is your age?\n')
age_plus_ten = str(int(age) + 10)
age_plus_twenty = str(int(age) + 20)
age_plus_thirty = str(int(age) + 30)
age_plus_forty = str(int(age) + 40)
print(f'You are {age} years old.')
print(f'In 10 years you will be {age_plus_ten}')
print(f'In 20 years you will be {age_plus_twenty}')
print(f'In 30 years you will be {age_plus_thirty}')
print(f'In 40 years you will be {age_plus_forty}')